site_name: ot1j9dc4rdqcs45pcvpho3jgr
theme:
  name: material

docs_dir: ot1j9dc4rdqcs45pcvpho3jgr

markdown_extensions:
  - pymdownx.snippets:
      base_path: ["."]

validation:
  nav:
    not_found: info
    omitted_files: info
  links:
    not_found: info

nav:
  - Home: index.md
  - Useage: useage.md
  - Conventions: conventions.md
  - Code of Conduct: code_of_conduct.md
  - Contributing: contributing.md
  - Contributors: contributors.md
  - Governance: governance.md
  - Labels: labels.md
  - Support: support.md
  - Ticketing: ticketing.md
  - Maintaining: maintaining.md
  - Security: security.md
  