site_name: ot1j9dc4rdqcs45pcvpho3jgr
theme:
  name: material

docs_dir: ot1j9dc4rdqcs45pcvpho3jgr

markdown_extensions:
  - pymdownx.snippets:
      base_path: ["."]

plugins:
  - search
  - monorepo    

validation:
  nav:
    not_found: info
    omitted_files: info
  links:
    not_found: info

nav:
  - '*import ot1j9dc4rdqcs45pcvpho3jgr/mkdocs.yml'
  - docs: '*import docs/mkdocs.yml'