version: 2

mkdocs:
  configuration: ot1j9dc4rdqcs45pcvpho3jgr/mkdocs.yaml

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  
  commands:
    - curl -fsSL https://pixi.sh/install.sh | bash
    - $HOME/.pixi/bin/pixi install -e dev
    - $HOME/.pixi/bin/pixi run -e dev build_docs --site-dir $READTHEDOCS_OUTPUT/html